### ISSUE TITLE
No module named 'sfast.utils.xformers_attention

### ISSUE THREAD

**Issue by ezra-ch** [gameltb/ComfyUI_stable_fast#9]
```  File "/home/peko/ComfyUI/custom_nodes/ComfyUI_stable_fast/module/stable_diffusion_pipeline_compiler.py", line 190, in build_lazy_trace_module
    from sfast.utils.xformers_attention import (
ModuleNotFoundError: No module named 'sfast.utils.xformers_attention'

Prompt executed in 2.32 seconds
```

![image](https://github.com/gameltb/ComfyUI_stable_fast/assets/69337319/e3305773-2aa5-47e2-ab15-5c30c9da5c56)

**Comment by ezra-ch** [comment]
its  in   adding 'sfast/libs/xformers/xformers_attention.py'

**Comment by ezra-ch** [comment]
Left with stablefast,  right without. seems to be 30% faster
![image](https://github.com/gameltb/ComfyUI_stable_fast/assets/69337319/b5710782-2693-4484-b1b1-e8bad24b74da)

**Comment by gameltb** [comment]
I fixed import in main. 
These outputs are fine for the current stable fast.
